---
language: python

env:
  global:
    - OSISM_VERSION=latest

install:
  - pip install -r requirements.txt

script:
  - bash scripts/trigger.sh

notifications:
  irc:
    channels:
      - "irc.freenode.org#osism"
    use_notice: true
