---
dist: xenial
language: python

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - scripts/travis.sh

env:
  global:
    - OSISM_VERSION=latest

install:
  - pip install -r requirements.txt

script:
  - 'if [[ "$TRAVIS_EVENT_TYPE" == "cron" || $FORCE_UPDATE_IMAGES == "true" ]]; then bash scripts/update-images.sh; fi'

notifications:
  irc:
    channels:
      - "irc.freenode.org#osism"
    template:
      - "%{result} %{repository_slug}: %{commit_subject} %{build_url}"
