---
ansible_version: '>=2.10,<2.11'
manager_version: latest
repository_version: latest

osism_projects:
  ara: 1.5.5
  docker: 5:20.10.0

docker_images:
  adminer: 4.7
  ara_server: 1.5.5
  awxclient: 16.0.0
  mariadb: 10.5
  netbox: v2.10
  nexus: 3.30.0
  nginx: 1.19-alpine
  phpmyadmin: 5.1
  postgres: 13-alpine
  redis: 6-alpine
  registry: 2.7

ansible_roles:
  ANXS.apt: f602ba7e88abfbb3af6679a8ca47207dc3e9d9c4
  geerlingguy.dotfiles: master
  hardening: 2093f503a64f213f58f9cab97a10a6f915a02ce9
  stackhpc.luks: master
