---
ansible_version: '>=2.7,<2.8'
repository_version: 2019.3.0

osism_projects:
  ara: 0.16.3
  docker: 5:18.09.4
  node_exporter: v0.17.0

docker_images:
  alertmanager: v0.15.3
  aptly: 1.3.0
  ara_server: 0.16.3
  blackbox-exporter: v0.12.0
  cadvisor: v0.31.0
  ceph_exporter: 2.0.1-luminous
  cobbler: 2.8
  devpi: 4.6.0
  haproxy_exporter: v0.9.0
  installer: 2019.3.0
  mariadb: 10.3.11
  memcached_exporter: v0.5.0
  mysqld_exporter: v0.11.0
  nexus: 3.15.2
  nginx: 1.13.12
  node_exporter: v0.17.0
  phpmyadmin: 4.8
  prometheus: v2.5.0
  redis: 4.0.11
  registry: 2.6.2

ansible_roles:
  ANXS.apt: f602ba7e88abfbb3af6679a8ca47207dc3e9d9c4
  ANXS.timezone: 9a77595bf89fc2c255c7c36c18a9cb113911144d
  ANXS.utilities: 8ec75691a6021aa0ba18214bdcba22242c2c5c10
  debops.grub: ee3d1c1071bda347d516e14bb3bc614d7d5fb47c
  hardening: 09051c5013869510f74592fa5e4f9ffaea4cd296
  osism.cobbler: v2019.3.0
  osism.cockpit: v2019.3.0
  osism.common: v2019.3.0
  osism.chrony: v2019.3.0
  osism.configuration: v2019.3.0
  osism.docker: v2019.3.0
  osism.helper: v2019.3.0
  osism.hostname: v2019.3.0
  osism.hosts: v2019.3.0
  osism.manager: v2019.3.0
  osism.mirror: v2019.3.0
  osism.monitoring: v2019.3.0
  osism.network-interfaces: v2019.3.0
  osism.operator: v2019.3.0
  osism.prometheus-exporter: v2019.3.0
  osism.prometheus: v2019.3.0
  osism.proxy: v2019.3.0
  osism.repository: v2019.3.0
  osism.resolvconf: v2019.3.0
